In [1]:
#Accessing the Data from DataFrame
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [2]:
#Get First FIVE Rows
a.head()

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77
3   103    Raji      56       78     34     56       88      55
4   104  Kalyan      51       63     62     93       67      51

In [3]:
#Get First Three Rows
a.head(3)

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77

In [4]:
#Get Last 5 Rows
a.tail()

    htno     name  telugu  english  hindi  maths  science  social
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [5]:
#Get Last 2 Rows
a.tail(2)

    htno    name  telugu  english  hindi  maths  science  social
15   114  Rajesh      45       67     77     55       66      46
16   115  Rakesh      67       78     88     78       67      49

In [6]:
#Get Last 6 Rows
a.tail(6)

    htno     name  telugu  english  hindi  maths  science  social
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [7]:
#Get the Descriptive Statistical Information about DataFrame Object
a.describe()

,htno,telugu,english,hindi,maths,science,social
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,107.294118,54.000000,70.705882,65.764706,82.235294,69.588235,59.882353
std,4.687279,7.141428,11.671358,20.504662,13.917298,14.339887,14.696438
min,100.000000,45.000000,48.000000,34.000000,55.000000,44.000000,35.000000
25%,104.000000,50.000000,63.000000,56.000000,76.000000,66.000000,49.000000
50%,107.000000,53.000000,67.000000,64.000000,87.000000,67.000000,55.000000
75%,111.000000,56.000000,78.000000,77.000000,93.000000,77.000000,73.000000
max,115.000000,67.000000,89.000000,99.000000,99.000000,98.000000,88.000000

In [8]:
#Get the Descriptive Statistical Information about DataFrame Object
a.describe(include="all")

,htno,name,telugu,english,hindi,maths,science,social
count,17.000000,17,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
unique,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Rajesh,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,107.294118,NaN,54.000000,70.705882,65.764706,82.235294,69.588235,59.882353
std,4.687279,NaN,7.141428,11.671358,20.504662,13.917298,14.339887,14.696438
min,100.000000,NaN,45.000000,48.000000,34.000000,55.000000,44.000000,35.000000
25%,104.000000,NaN,50.000000,63.000000,56.000000,76.000000,66.000000,49.000000
50%,107.000000,NaN,53.000000,67.000000,64.000000,87.000000,67.000000,55.000000
75%,111.000000,NaN,56.000000,78.000000,77.000000,93.000000,77.000000,73.000000
max,115.000000,NaN,67.000000,89.000000,99.000000,99.000000,98.000000,88.000000

In [9]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [10]:
a.shape

(17, 8)

In [11]:
print("Number of Rows=",a.shape[0])
print("Number of Columns=",a.shape[1])

Number of Rows= 17
Number of Columns= 8

In [12]:
a.columns

Index(['htno', 'name', 'telugu', 'english', 'hindi', 'maths', 'science',
       'social'],
      dtype='str')

In [13]:
for cn in a.columns:
    print(cn)

htno
name
telugu
english
hindi
maths
science
social

In [14]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [15]:
#Access the Data from DataFrame Object By using Slicing
a[0:6]

   htno     name  telugu  english  hindi  maths  science  social
0   100   Ramesh      50       60     66     98       66      55
1   101   Rajesh      45       67     34     67       66      78
2   102   Rossum      56       88     56     99       44      77
3   103     Raji      56       78     34     56       88      55
4   104   Kalyan      51       63     62     93       67      51
5   105  Karthik      48       62     39     68       65      88

In [16]:
a[0:3]

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55
1   101  Rajesh      45       67     34     67       66      78
2   102  Rossum      56       88     56     99       44      77

In [17]:
a[0:1]

   htno    name  telugu  english  hindi  maths  science  social
0   100  Ramesh      50       60     66     98       66      55

In [18]:
a[::2]

    htno    name  telugu  english  hindi  maths  science  social
0    100  Ramesh      50       60     66     98       66      55
2    102  Rossum      56       88     56     99       44      77
4    104  Kalyan      51       63     62     93       67      51
6    106  Kambli      53       81     59     92       48      73
8    108  Ganesh      53       62     76     88       76      35
10   110   Biswa      66       48     86     95       48      47
12   104  Kalyan      51       63     62     93       67      51
14   113    sonu      60       89     98     87       77      68
16   115  Rakesh      67       78     88     78       67      49

In [19]:
a[::-1]

    htno     name  telugu  english  hindi  maths  science  social
16   115   Rakesh      67       78     88     78       67      49
15   114   Rajesh      45       67     77     55       66      46
14   113     sonu      60       89     98     87       77      68
13   112  shareef      50       63     99     90       76      67
12   104   Kalyan      51       63     62     93       67      51
11   111   Ritchi      66       68     64     76       98      75
10   110    Biswa      66       48     86     95       48      47
9    109     Nags      55       77     44     77       86      58
8    108   Ganesh      53       62     76     88       76      35
7    107  Praveen      46       88     74     86       78      45
6    106   Kambli      53       81     59     92       48      73
5    105  Karthik      48       62     39     68       65      88
4    104   Kalyan      51       63     62     93       67      51
3    103     Raji      56       78     34     56       88      55
2    102   Rossum      56       88     56     99       44      77
1    101   Rajesh      45       67     34     67       66      78
0    100   Ramesh      50       60     66     98       66      55

In [20]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [21]:
#Get the Name of Students
print(a["name"],type(a["name"]))

0      Ramesh
1      Rajesh
2      Rossum
3        Raji
4      Kalyan
5     Karthik
6      Kambli
7     Praveen
8      Ganesh
9        Nags
10      Biswa
11     Ritchi
12     Kalyan
13    shareef
14       sonu
15     Rajesh
16     Rakesh
Name: name, dtype: str <class 'pandas.Series'>

In [22]:
for names in a["name"].values:
    print(names)

Ramesh
Rajesh
Rossum
Raji
Kalyan
Karthik
Kambli
Praveen
Ganesh
Nags
Biswa
Ritchi
Kalyan
shareef
sonu
Rajesh
Rakesh

In [23]:
for names in a["name"].values:
    print(names.upper())

RAMESH
RAJESH
ROSSUM
RAJI
KALYAN
KARTHIK
KAMBLI
PRAVEEN
GANESH
NAGS
BISWA
RITCHI
KALYAN
SHAREEF
SONU
RAJESH
RAKESH

In [24]:
#Get Maths Marks from DataFrame
a["maths"]

0     98
1     67
2     99
3     56
4     93
5     68
6     92
7     86
8     88
9     77
10    95
11    76
12    93
13    90
14    87
15    55
16    78
Name: maths, dtype: int64

In [25]:
for marks in a["maths"].values:
    print(marks)

98
67
99
56
93
68
92
86
88
77
95
76
93
90
87
55
78

In [27]:
#Get Names and Maths Marks
a[["name","maths"]]

       name  maths
0    Ramesh     98
1    Rajesh     67
2    Rossum     99
3      Raji     56
4    Kalyan     93
5   Karthik     68
6    Kambli     92
7   Praveen     86
8    Ganesh     88
9      Nags     77
10    Biswa     95
11   Ritchi     76
12   Kalyan     93
13  shareef     90
14     sonu     87
15   Rajesh     55
16   Rakesh     78

In [28]:
#Get Names and Maths Marks and science marks
a[["name","maths","science"]]

       name  maths  science
0    Ramesh     98       66
1    Rajesh     67       66
2    Rossum     99       44
3      Raji     56       88
4    Kalyan     93       67
5   Karthik     68       65
6    Kambli     92       48
7   Praveen     86       78
8    Ganesh     88       76
9      Nags     77       86
10    Biswa     95       48
11   Ritchi     76       98
12   Kalyan     93       67
13  shareef     90       76
14     sonu     87       77
15   Rajesh     55       66
16   Rakesh     78       67

In [29]:
#Get the Records from 5th Record to 10th Record with Name,Maths and social
a[["name","maths","social"]][5:11]

       name  maths  social
5   Karthik     68      88
6    Kambli     92      73
7   Praveen     86      45
8    Ganesh     88      35
9      Nags     77      58
10    Biswa     95      47

In [30]:
#Get the Name, English and Maths Maths of 15th Record
a[["name","english","maths"]][15:16]

      name  english  maths
15  Rajesh       67     55

In [31]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49