In [2]:
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [4]:
#Compute total marks of all students by adding new col 'total'
a["total"]=0.0
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total
0    100   Ramesh      50       60     66     98       66      55    0.0
1    101   Rajesh      45       67     34     67       66      78    0.0
2    102   Rossum      56       88     56     99       44      77    0.0
3    103     Raji      56       78     34     56       88      55    0.0
4    104   Kalyan      51       63     62     93       67      51    0.0
5    105  Karthik      48       62     39     68       65      88    0.0
6    106   Kambli      53       81     59     92       48      73    0.0
7    107  Praveen      46       88     74     86       78      45    0.0
8    108   Ganesh      53       62     76     88       76      35    0.0
9    109     Nags      55       77     44     77       86      58    0.0
10   110    Biswa      66       48     86     95       48      47    0.0
11   111   Ritchi      66       68     64     76       98      75    0.0
12   104   Kalyan      51       63     62     93       67      51    0.0
13   112  shareef      50       63     99     90       76      67    0.0
14   113     sonu      60       89     98     87       77      68    0.0
15   114   Rajesh      45       67     77     55       66      46    0.0
16   115   Rakesh      67       78     88     78       67      49    0.0

In [6]:
a["total"]=a["telugu"]+a["english"]+a["hindi"]+a["maths"]+a["science"]+a["social"]
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

In [7]:
#Calculate percent by adding new Column 'percent'
a["percent"]=(a["total"]/600)*100
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

      percent
0   65.833333
1   59.500000
2   70.000000
3   61.166667
4   64.500000
5   61.666667
6   67.666667
7   69.500000
8   65.000000
9   66.166667
10  65.000000
11  74.500000
12  64.500000
13  74.166667
14  79.833333
15  59.333333
16  71.166667

In [9]:
import numpy as np
a["percent"]=np.around((a["total"]/600)*100,2)
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent
0     65.83
1     59.50
2     70.00
3     61.17
4     64.50
5     61.67
6     67.67
7     69.50
8     65.00
9     66.17
10    65.00
11    74.50
12    64.50
13    74.17
14    79.83
15    59.33
16    71.17

In [10]:
a["grade"]=None
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent grade
0     65.83  None
1     59.50  None
2     70.00  None
3     61.17  None
4     64.50  None
5     61.67  None
6     67.67  None
7     69.50  None
8     65.00  None
9     66.17  None
10    65.00  None
11    74.50  None
12    64.50  None
13    74.17  None
14    79.83  None
15    59.33  None
16    71.17  None

In [11]:
#Filtering the Data from DataFrame with Condition

In [14]:
#Get the Students Details who secured More than 85 in Maths
a.loc[a["maths"]>85]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
0,100,Ramesh,50,60,66,98,66,55,395,65.83,None
2,102,Rossum,56,88,56,99,44,77,420,70.00,None
4,104,Kalyan,51,63,62,93,67,51,387,64.50,None
6,106,Kambli,53,81,59,92,48,73,406,67.67,None
7,107,Praveen,46,88,74,86,78,45,417,69.50,None
8,108,Ganesh,53,62,76,88,76,35,390,65.00,None
10,110,Biswa,66,48,86,95,48,47,390,65.00,None
12,104,Kalyan,51,63,62,93,67,51,387,64.50,None
13,112,shareef,50,63,99,90,76,67,445,74.17,None
14,113,sonu,60,89,98,87,77,68,479,79.83,None

In [15]:
#Get the Students Details who secured More than 95 in Maths
a.loc[a["maths"]>95]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
0,100,Ramesh,50,60,66,98,66,55,395,65.83,None
2,102,Rossum,56,88,56,99,44,77,420,70.00,None

In [16]:
#Get the Students Details who secured More than 100 in Maths
a.loc[a["maths"]==100]

Empty DataFrame
Columns: [htno, name, telugu, english, hindi, maths, science, social, total, percent, grade]
Index: []

In [17]:
#Get the Students Details who secured Maths Marke Between 90 and 75
(a["maths"]>=75) & (a["maths"]<=90)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10    False
11     True
12    False
13     True
14     True
15    False
16     True
Name: maths, dtype: bool

In [18]:
#Get the Students Details who secured Maths Marke Between 90 and 75
a.loc[(a["maths"]>75)&(a["maths"]<=90)]

,htno,name,telugu,english,hindi,maths,science,social,total,percent,grade
7,107,Praveen,46,88,74,86,78,45,417,69.50,None
8,108,Ganesh,53,62,76,88,76,35,390,65.00,None
9,109,Nags,55,77,44,77,86,58,397,66.17,None
11,111,Ritchi,66,68,64,76,98,75,447,74.50,None
13,112,shareef,50,63,99,90,76,67,445,74.17,None
14,113,sonu,60,89,98,87,77,68,479,79.83,None
16,115,Rakesh,67,78,88,78,67,49,427,71.17,None

In [19]:
#Get the Students  Name and Maths Marks who secured Maths Marke Between 90 and 75
a.loc[(a["maths"]>75)&(a["maths"]<=90),["name","maths"]]

       name  maths
7   Praveen     86
8    Ganesh     88
9      Nags     77
11   Ritchi     76
13  shareef     90
14     sonu     87
16   Rakesh     78

In [21]:
#Get the Students  Name and English Marks >=80
a.loc[(a["english"]>=80),["name"]]

       name
2    Rossum
6    Kambli
7   Praveen
14     sonu

In [22]:
#Get then Student Name and totalmarks whose total marks >=400
a.loc[a["total"]>=400,["name","total"]]

       name  total
2    Rossum    420
6    Kambli    406
7   Praveen    417
11   Ritchi    447
13  shareef    445
14     sonu    479
16   Rakesh    427

In [24]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent grade
0     65.83  None
1     59.50  None
2     70.00  None
3     61.17  None
4     64.50  None
5     61.67  None
6     67.67  None
7     69.50  None
8     65.00  None
9     66.17  None
10    65.00  None
11    74.50  None
12    64.50  None
13    74.17  None
14    79.83  None
15    59.33  None
16    71.17  None

In [25]:
#Decide the Grading based the following Conditions
# if percent ranges between 75.0 to 100.0 then Given Distinction
# if percent ranges between 70.0 to 75.0(Excluded) then Given First
# if percent ranges between 60.0 to 70.0(Excluded) then Given Second
# if percent  <60(Excluded) then Given Third

In [27]:
# if percent ranges between 75.0 to 100.0 then Given Distinction
a.loc[(a["percent"]<=100)&(a["percent"]>=75),["grade"]]="DISTINCTION"
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent        grade
0     65.83         None
1     59.50         None
2     70.00         None
3     61.17         None
4     64.50         None
5     61.67         None
6     67.67         None
7     69.50         None
8     65.00         None
9     66.17         None
10    65.00         None
11    74.50         None
12    64.50         None
13    74.17         None
14    79.83  DISTINCTION
15    59.33         None
16    71.17         None

In [28]:
# if percent ranges between 70.0 to 75.0(Excluded) then Given First
a.loc[(a["percent"]>=70)&(a["percent"]<75),["grade"]]="FIRST"
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent        grade
0     65.83         None
1     59.50         None
2     70.00        FIRST
3     61.17         None
4     64.50         None
5     61.67         None
6     67.67         None
7     69.50         None
8     65.00         None
9     66.17         None
10    65.00         None
11    74.50        FIRST
12    64.50         None
13    74.17        FIRST
14    79.83  DISTINCTION
15    59.33         None
16    71.17        FIRST

In [32]:
# if percent ranges between 60.0 to 70.0(Excluded) then Given Second
a.loc[(a["percent"]>=60)&(a["percent"]<70),["grade"]]="SECOND"
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent        grade
0     65.83       SECOND
1     59.50         None
2     70.00       SECOND
3     61.17       SECOND
4     64.50       SECOND
5     61.67       SECOND
6     67.67       SECOND
7     69.50       SECOND
8     65.00       SECOND
9     66.17       SECOND
10    65.00       SECOND
11    74.50       SECOND
12    64.50       SECOND
13    74.17       SECOND
14    79.83  DISTINCTION
15    59.33         None
16    71.17       SECOND

In [34]:
# if percent <60(Excluded) then Given Third
a.loc[(a["percent"]<60),["grade"]]="THIRD"
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent        grade
0     65.83       SECOND
1     59.50        THIRD
2     70.00       SECOND
3     61.17       SECOND
4     64.50       SECOND
5     61.67       SECOND
6     67.67       SECOND
7     69.50       SECOND
8     65.00       SECOND
9     66.17       SECOND
10    65.00       SECOND
11    74.50       SECOND
12    64.50       SECOND
13    74.17       SECOND
14    79.83  DISTINCTION
15    59.33        THIRD
16    71.17       SECOND

In [36]:
#Get Names and Grades of all Students
a.loc[::,["name","grade"]]

       name        grade
0    Ramesh       SECOND
1    Rajesh        THIRD
2    Rossum       SECOND
3      Raji       SECOND
4    Kalyan       SECOND
5   Karthik       SECOND
6    Kambli       SECOND
7   Praveen       SECOND
8    Ganesh       SECOND
9      Nags       SECOND
10    Biswa       SECOND
11   Ritchi       SECOND
12   Kalyan       SECOND
13  shareef       SECOND
14     sonu  DISTINCTION
15   Rajesh        THIRD
16   Rakesh       SECOND

In [37]:
#Get Names and Grades of all Students
a[["name","grade"]]

       name        grade
0    Ramesh       SECOND
1    Rajesh        THIRD
2    Rossum       SECOND
3      Raji       SECOND
4    Kalyan       SECOND
5   Karthik       SECOND
6    Kambli       SECOND
7   Praveen       SECOND
8    Ganesh       SECOND
9      Nags       SECOND
10    Biswa       SECOND
11   Ritchi       SECOND
12   Kalyan       SECOND
13  shareef       SECOND
14     sonu  DISTINCTION
15   Rajesh        THIRD
16   Rakesh       SECOND

In [38]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent        grade
0     65.83       SECOND
1     59.50        THIRD
2     70.00       SECOND
3     61.17       SECOND
4     64.50       SECOND
5     61.67       SECOND
6     67.67       SECOND
7     69.50       SECOND
8     65.00       SECOND
9     66.17       SECOND
10    65.00       SECOND
11    74.50       SECOND
12    64.50       SECOND
13    74.17       SECOND
14    79.83  DISTINCTION
15    59.33        THIRD
16    71.17       SECOND

In [40]:
#Export OR Save the DataFrame Data to the CSV File--we use to_csv() Present in DataFrame Object
a.to_csv("F:\\Python-Libraries\\Pandas\\StudentsResult.csv")
print("DataFrame Data Exported to CSV File")

DataFrame Data Exported to CSV File

In [41]:
#Export OR Save the DataFrame Data to the excel File--we use to_excel() Present in DataFrame Object
a.to_excel("F:\\Python-Libraries\\Pandas\\Stud.xlsx")
print("DataFrame Data Exported to EXCEL File")

DataFrame Data Exported to EXCEL File