In [1]:
import numpy as np
import pandas as pd
d={"First Score":[100,90,np.nan,95],
   "Second Score":[30,np.nan,45,56],
   "Third Score":[52,34,1,98],
   "Fourth Score":[np.nan,np.nan,np.nan,65]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           34           NaN
2          NaN          45.0            1           NaN
3         95.0          56.0           98          65.0

In [2]:
a.dropna()   #By Default the axis=0 that is row

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [3]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           34           NaN
2          NaN          45.0            1           NaN
3         95.0          56.0           98          65.0

In [4]:
a.dropna(inplace=True)

In [5]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [6]:
import numpy as np
import pandas as pd
d = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [10]:
a.dropna(axis=0,inplace=True)

In [11]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [12]:
import numpy as np
import pandas as pd
d = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [14]:
a.dropna(axis=1)    #Here axis=1 Represents columns

   Third Score
0           52
1           40
2           80
3           98

In [15]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [16]:
a.dropna(axis=1,inplace=True)

In [17]:
print(a)

   Third Score
0           52
1           40
2           80
3           98

In [18]:
import numpy as np
import pandas as pd
d = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [19]:
a.dropna(how="any")   # default Value of 'how' argument is 'any' and default axis is 0 (row)

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [20]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [21]:
import numpy as np
import pandas as pd
d = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [22]:
a.dropna(how="all")

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [23]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [24]:
import numpy as np
import pandas as pd
d = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, np.nan]}
a=pd.DataFrame(d)
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98           NaN

In [25]:
a.dropna(how="all")

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98           NaN

In [26]:
print(a)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98           NaN

In [27]:
a.dropna(axis=1,how="all")

   First Score  Second Score  Third Score
0        100.0          30.0           52
1         90.0           NaN           40
2          NaN          45.0           80
3         95.0          56.0           98

In [28]:
a.dropna(axis=1,how="all",inplace=True)

In [29]:
print(a)

   First Score  Second Score  Third Score
0        100.0          30.0           52
1         90.0           NaN           40
2          NaN          45.0           80
3         95.0          56.0           98