In [1]:
#EDA--Employee Salary Analaysis Project
import numpy as np
import pandas as pd
pd.set_option("display.max_columns",None)

In [2]:
#Read the Salaries Dataset 
import pandas as pd
csv=pd.read_csv("F:\\Python-Libraries\\Pandas\\Salaries.csv")
print(csv)

            Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60
...                                                ...        ...
148649                                       Custodian       0.00
148650                                    Not provided        NaN
148651                                    Not provided        NaN
148652                                    Not provided        NaN
148653                      Counselor, Log Cabin Ranch       0.00

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011
1         245131.88  137811.38       NaN  538909.28         538909.28  2011
2         106088.18   16452.60       NaN  335279.91         335279.91  2011
3          56120.71  198306.90       NaN  332343.61         332343.61  2011
4           9737.00  182234.59       NaN  326373.19         326373.19  2011
...             ...        ...       ...        ...               ...   ...
148649         0.00       0.00       0.0       0.00              0.00  2014
148650          NaN        NaN       NaN       0.00              0.00  2014
148651          NaN        NaN       NaN       0.00              0.00  2014
148652          NaN        NaN       NaN       0.00              0.00  2014
148653         0.00    -618.13       0.0    -618.13           -618.13  2014

        Notes         Agency  Status
0         NaN  San Francisco     NaN
1         NaN  San Francisco     NaN
2         NaN  San Francisco     NaN
3         NaN  San Francisco     NaN
4         NaN  San Francisco     NaN
...       ...            ...     ...
148649    NaN  San Francisco     NaN
148650    NaN  San Francisco     NaN
148651    NaN  San Francisco     NaN
148652    NaN  San Francisco     NaN
148653    NaN  San Francisco     NaN

[148654 rows x 13 columns]

In [3]:
#1.  Display Top 10 Rows of The Dataset
csv.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [4]:
#OR
csv.loc[0:9]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [5]:
#OR 
csv.iloc[0:10]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [6]:
#2. Check Last 10 Rows of The Dataset
csv.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [7]:
#OR 
csv.loc[len(csv)-10:]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [8]:
#OR
csv.iloc[len(csv)-10:]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [9]:
#3. Find Shape of Our Dataset (Number of Rows And Number of Columns)
csv.shape

(148654, 13)

In [10]:
print("Number of Rows in Dataset=",csv.shape[0])
print("Number of Columns in Dataset=",csv.shape[1])

Number of Rows in Dataset= 148654
Number of Columns in Dataset= 13

In [11]:
#4.  Getting Information About Our Dataset Like Total Number Rows, 
# Total Number of Columns, Datatypes of Each Column And  Memory Requirement
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), str(3)
memory usage: 21.3 MB

In [12]:
#5. Check Null Values In The Dataset
csv.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [13]:
#OR 
csv.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [14]:
#6. Drop ID, Notes, Agency, and Status Columns
csv.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [15]:
csv.drop(["Id","Notes","Agency","Status"],axis=1,inplace=True)

In [16]:
print(csv)

             EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
...                   ...                                             ...
148649      Roy I Tillery                                       Custodian
148650       Not provided                                    Not provided
148651       Not provided                                    Not provided
148652       Not provided                                    Not provided
148653          Joe Lopez                      Counselor, Log Cabin Ranch

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43
1       155966.02    245131.88  137811.38       NaN  538909.28
2       212739.13    106088.18   16452.60       NaN  335279.91
3        77916.00     56120.71  198306.90       NaN  332343.61
4       134401.60      9737.00  182234.59       NaN  326373.19
...           ...          ...        ...       ...        ...
148649       0.00         0.00       0.00       0.0       0.00
148650        NaN          NaN        NaN       NaN       0.00
148651        NaN          NaN        NaN       NaN       0.00
148652        NaN          NaN        NaN       NaN       0.00
148653       0.00         0.00    -618.13       0.0    -618.13

        TotalPayBenefits  Year
0              567595.43  2011
1              538909.28  2011
2              335279.91  2011
3              332343.61  2011
4              326373.19  2011
...                  ...   ...
148649              0.00  2014
148650              0.00  2014
148651              0.00  2014
148652              0.00  2014
148653           -618.13  2014

[148654 rows x 9 columns]

In [17]:
print("Number of Rows in Dataset=",csv.shape[0])
print("Number of Columns in Dataset=",csv.shape[1])

Number of Rows in Dataset= 148654
Number of Columns in Dataset= 9

In [18]:
#7. Get Overall Statistics About The Dataframe
csv.describe()

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
mean,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

In [19]:
#OR
csv.describe(include="all")

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
unique,110811,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,13,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,NaN,NaN,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,NaN,NaN,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

In [20]:
#8. Find Occurrence of The Employee Names  (Top 5)
csv["EmployeeName"].value_counts()

EmployeeName
Kevin Lee             13
Steven Lee            11
William Wong          11
Richard Lee           11
KEVIN LEE              9
                      ..
Afakasi O Afakasi      1
Kenneth Mackey         1
Mark W Mcclure         1
Charlene D Mccully     1
Joe Lopez              1
Name: count, Length: 110811, dtype: int64

In [21]:
csv["EmployeeName"].value_counts().head()

EmployeeName
Kevin Lee       13
Steven Lee      11
William Wong    11
Richard Lee     11
KEVIN LEE        9
Name: count, dtype: int64

In [22]:
#9. Find The Number of Unique Job Titles
print("The Number of Unique Job Titles=",csv["JobTitle"].nunique())

The Number of Unique Job Titles= 2159

In [23]:
csv["JobTitle"].unique()

<ArrowStringArray>
[  'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
                  'CAPTAIN III (POLICE DEPARTMENT)',
             'WIRE ROPE CABLE MAINTENANCE MECHANIC',
     'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
                        'ASSISTANT DEPUTY CHIEF II',
               'BATTALION CHIEF, (FIRE DEPARTMENT)',
                   'DEPUTY DIRECTOR OF INVESTMENTS',
           'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
                      'EXECUTIVE CONTRACT EMPLOYEE',
 ...
                      'Hospital Eligibility Worker',
                                'Personnel Trainee',
                      'ACPO,JuvP, Juv Prob (SFERS)',
                        'Apprentice Cement Mason I',
                         'Marina Associate Manager',
                     'Sr Cnselor, Juv Hall (SFERS)',
                   'Forensic Toxicologist Supervis',
                                       'Conversion',
                                        'Cashier 3',
                                     'Not provided']
Length: 2159, dtype: str

In [24]:
#10.Total Number of Job Titles Contain Captain
csv["JobTitle"].str.contains("CAPTAIN",case=False)

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [26]:
csv[csv["JobTitle"].str.contains("CAPTAIN")]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
8684,JEANNE SEYLER,"CAPTAIN, FIRE SUPPRESSION",95055.34,0.00,9197.14,NaN,104252.48,104252.48,2011
10485,JANE SMITH,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",74592.00,1538.59,18804.68,NaN,94935.27,94935.27,2011
11198,KATHRYN BROWN,CAPTAIN III (POLICE DEPARTMENT),10684.50,0.00,81244.87,NaN,91929.37,91929.37,2011
31297,MARCO CARNIGLIA,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",9839.72,0.00,1203.77,NaN,11043.49,11043.49,2011
34124,JOHN FORBES-3,"CAPTAIN, FIRE SUPPRESSION",0.00,982.06,2277.34,NaN,3259.40,3259.40,2011

In [27]:
csv[csv["JobTitle"].str.contains("CAPTAIN",case=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
116604,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014
120867,Michael J Moran,Captain 3,7660.00,1496.09,126560.36,2189.51,135716.45,137905.96,2014
122361,Michael V Rolovich,"Captain, Fire Suppression",0.00,0.00,130320.75,0.00,130320.75,130320.75,2014
126588,Stephen M Tittel,Captain 3,68491.89,0.00,23721.91,19020.79,92213.80,111234.59,2014
132232,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014

In [29]:
print("Total Number of JobTitle Contains 'CAPTAIN'=",len(csv[csv["JobTitle"].str.contains("Captain",case=False)]))

Total Number of JobTitle Contains 'CAPTAIN'= 552

In [31]:
#11. Display All the Employee Names From Fire Department
csv[csv["JobTitle"].str.contains("Fire",case=False)]["EmployeeName"]

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: str

In [33]:
csv[csv["JobTitle"].str.contains("Fire",case=False)]["EmployeeName"].values

<ArrowStringArray>
[   'PATRICK GARDNER',          'ALSON LEE',     'MICHAEL MORRIS',
 'JOANNE HAYES-WHITE',      'ARTHUR KENNEY',     'DAVID FRANKLIN',
         'MARTY ROSS',      'GEORGE GARCIA',      'VICTOR WYRSCH',
    'JOSEPH DRISCOLL',
 ...
    'Clyde M Watarai',   'Kirsten K Conroy',      'Thomas Burger',
      'Denise Elarms',  'Claudia Valentino',   'Kenneth C Farris',
      'Edward A Dunn',     'Kari A Johnson',       'Sheryl K Lee',
    'Lawrence F Gatt']
Length: 5879, dtype: str

In [34]:
len(csv[csv["JobTitle"].str.contains("Fire",case=False)]["EmployeeName"])

5879

In [38]:
print("Number of People Working Fire Department=",len(csv[csv["JobTitle"].str.contains("Fire",case=False)]["EmployeeName"]))

Number of People Working Fire Department= 5879

In [39]:
#11. Display All the Employee Names From Fire Department
csv[csv["JobTitle"].str.contains("Fire",case=False)][["EmployeeName","JobTitle"]]

              EmployeeName                                          JobTitle
4          PATRICK GARDNER      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
6                ALSON LEE                BATTALION CHIEF, (FIRE DEPARTMENT)
8           MICHAEL MORRIS                BATTALION CHIEF, (FIRE DEPARTMENT)
9       JOANNE HAYES-WHITE            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
10           ARTHUR KENNEY  ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
...                    ...                                               ...
145956    Kenneth C Farris                                       Firefighter
147556       Edward A Dunn                                       Firefighter
148021      Kari A Johnson                                       Firefighter
148209        Sheryl K Lee                                       Firefighter
148554     Lawrence F Gatt                             Fire Alarm Dispatcher

[5879 rows x 2 columns]

In [41]:
#12. Find Minimum, Maximum, and Average BasePay
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [43]:
csv["BasePay"].max()

np.float64(319275.01)

In [44]:
csv["BasePay"].min()

np.float64(-166.01)

In [46]:
csv["BasePay"].mean()

np.float64(66325.44884048769)

In [47]:
print("Maximum BasePay=",csv["BasePay"].max())
print("Minimum BasePay=",csv["BasePay"].min())
print("Average BasePay=",csv["BasePay"].mean())

Maximum BasePay= 319275.01
Minimum BasePay= -166.01
Average BasePay= 66325.44884048769

In [48]:
csv["BasePay"].describe()

count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

In [49]:
csv["BasePay"].describe()["count"]

np.float64(148045.0)

In [50]:
csv["BasePay"].describe()["max"]

np.float64(319275.01)

In [51]:
csv["BasePay"].describe()["min"]

np.float64(-166.01)

In [52]:
csv["BasePay"].describe()["mean"]

np.float64(66325.44884048769)

In [53]:
print("Maximum BasePay=",csv["BasePay"].describe()["max"])
print("Minimum BasePay=",csv["BasePay"].describe()["min"])
print("Average BasePay=",csv["BasePay"].describe()["mean"])

Maximum BasePay= 319275.01
Minimum BasePay= -166.01
Average BasePay= 66325.44884048769

In [55]:
#13. Replace 'Not Provided' in EmployeeName' Column to NaN 
import numpy as np
csv["EmployeeName"].replace("Not Provided",np.nan)

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: str

In [56]:
print(csv)

             EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
...                   ...                                             ...
148649      Roy I Tillery                                       Custodian
148650       Not provided                                    Not provided
148651       Not provided                                    Not provided
148652       Not provided                                    Not provided
148653          Joe Lopez                      Counselor, Log Cabin Ranch

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43
1       155966.02    245131.88  137811.38       NaN  538909.28
2       212739.13    106088.18   16452.60       NaN  335279.91
3        77916.00     56120.71  198306.90       NaN  332343.61
4       134401.60      9737.00  182234.59       NaN  326373.19
...           ...          ...        ...       ...        ...
148649       0.00         0.00       0.00       0.0       0.00
148650        NaN          NaN        NaN       NaN       0.00
148651        NaN          NaN        NaN       NaN       0.00
148652        NaN          NaN        NaN       NaN       0.00
148653       0.00         0.00    -618.13       0.0    -618.13

        TotalPayBenefits  Year
0              567595.43  2011
1              538909.28  2011
2              335279.91  2011
3              332343.61  2011
4              326373.19  2011
...                  ...   ...
148649              0.00  2014
148650              0.00  2014
148651              0.00  2014
148652              0.00  2014
148653           -618.13  2014

[148654 rows x 9 columns]

In [57]:
#14. Drop The Rows Having 5 Missing Values
csv.isnull().sum(axis=1)==5

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Length: 148654, dtype: bool

In [58]:
csv[csv.isnull().sum(axis=1)==5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [59]:
#scsv.drop([scsv.isnull().sum(axis=1)==5],axis=0)  # Gives KeyError

In [60]:
csv.drop(csv[csv.isnull().sum(axis=1)==5].index,axis=0)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

In [61]:
csv.drop(csv[csv.isnull().sum(axis=1)==5].index,axis=0,inplace=True)

In [62]:
print("Number of Rows after Removing Rows with 5 Missing Values=",csv.shape[0])

Number of Rows after Removing Rows with 5 Missing Values= 148654

In [63]:
#15. Find Job Title of  an employee 'ALBERT PARDINI'
csv["EmployeeName"]=="ALBERT PARDINI"

0         False
1         False
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

In [64]:
csv[csv["EmployeeName"]=="ALBERT PARDINI"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [65]:
csv[csv["EmployeeName"]=="ALBERT PARDINI"]["JobTitle"]

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: str

In [66]:
#16. How Much ALBERT PARDINI Make (Include Benefits)?
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [75]:
csv[csv["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [77]:
#17.Display Name of The Person Having The Highest BasePay
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [78]:
csv["BasePay"].max()

np.float64(319275.01)

In [79]:
csv["BasePay"].max()==csv["BasePay"]

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: BasePay, Length: 148654, dtype: bool

In [80]:
csv[csv["BasePay"].max()==csv["BasePay"]]["EmployeeName"]

72925    Gregory P Suhr
Name: EmployeeName, dtype: str

In [81]:
#18.Find Average BasePay of All Employee Per Year 
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [84]:
csv.groupby("Year")["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [85]:
#19. Find Average BasePay of All Employee Per JobTitle 
csv.groupby("JobTitle")["BasePay"].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2159, dtype: float64

In [86]:
#20. Find Average BasePay of Employee Having Job Title ACCOUNTANT  
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [87]:
csv["JobTitle"]=="ACCOUNTANT"

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [89]:
csv[csv["JobTitle"]=="ACCOUNTANT"]["BasePay"].mean()

np.float64(46643.172)

In [90]:
#21. Find Top 5 Most Common Jobs
csv.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [91]:
csv["JobTitle"].value_counts()

JobTitle
Transit Operator                  7036
Special Nurse                     4389
Registered Nurse                  3736
Public Svc Aide-Public Works      2518
Police Officer 3                  2421
                                  ...
Marina Associate Manager             1
Sr Cnselor, Juv Hall (SFERS)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 2159, dtype: int64

In [92]:
csv["JobTitle"].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64