In [1]:
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [5]:
#Get 4th Records
a.iloc[4]

htno          104
name       Kalyan
telugu         51
english        63
hindi          62
maths          93
science        67
social         51
Name: 4, dtype: object

In [6]:
#Get 15 Record
a.iloc[15]

htno          114
name       Rajesh
telugu         45
english        67
hindi          77
maths          55
science        66
social         46
Name: 15, dtype: object

In [7]:
#Get 4th Record Name
a.iloc[4,1]

'Kalyan'

In [8]:
#Get 4th Record Name and Maths Marks
a.iloc[4,[1,5]]

name     Kalyan
maths        93
Name: 4, dtype: object

In [9]:
#Get 4th Record Name and Maths Marks and social
a.iloc[4,[1,5,7]]

name      Kalyan
maths         93
social        51
Name: 4, dtype: object

In [10]:
#Get 15th Record Name and Hindi
a.iloc[15,[1,4]]

name     Rajesh
hindi        77
Name: 15, dtype: object

In [11]:
#Get 5th Record to 10th Record
a.iloc[5:11]

    htno     name  telugu  english  hindi  maths  science  social
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47

In [13]:
#Get 11th record to 6th Record
a.iloc[11:5:-1]

    htno     name  telugu  english  hindi  maths  science  social
11   111   Ritchi      66       68     64     76       98      75
10   110    Biswa      66       48     86     95       48      47
9    109     Nags      55       77     44     77       86      58
8    108   Ganesh      53       62     76     88       76      35
7    107  Praveen      46       88     74     86       78      45
6    106   Kambli      53       81     59     92       48      73

In [14]:
#Get 11th record to 6th Record
a.iloc[6:12][::-1]

    htno     name  telugu  english  hindi  maths  science  social
11   111   Ritchi      66       68     64     76       98      75
10   110    Biswa      66       48     86     95       48      47
9    109     Nags      55       77     44     77       86      58
8    108   Ganesh      53       62     76     88       76      35
7    107  Praveen      46       88     74     86       78      45
6    106   Kambli      53       81     59     92       48      73

In [16]:
#Get 6th Record to 11th Record only Names
a.iloc[6:12,1]

6      Kambli
7     Praveen
8      Ganesh
9        Nags
10      Biswa
11     Ritchi
Name: name, dtype: str

In [17]:
#Get 6th Record to 11th Record only Names and Maths Marks
a.iloc[6:12,[1,5]]

       name  maths
6    Kambli     92
7   Praveen     86
8    Ganesh     88
9      Nags     77
10    Biswa     95
11   Ritchi     76

In [18]:
a.iloc[::,[1,5]]

       name  maths
0    Ramesh     98
1    Rajesh     67
2    Rossum     99
3      Raji     56
4    Kalyan     93
5   Karthik     68
6    Kambli     92
7   Praveen     86
8    Ganesh     88
9      Nags     77
10    Biswa     95
11   Ritchi     76
12   Kalyan     93
13  shareef     90
14     sonu     87
15   Rajesh     55
16   Rakesh     78

In [23]:
#Get all the Records with the Column Names from HTNO to Maths
a.iloc[::,0:6]

    htno     name  telugu  english  hindi  maths
0    100   Ramesh      50       60     66     98
1    101   Rajesh      45       67     34     67
2    102   Rossum      56       88     56     99
3    103     Raji      56       78     34     56
4    104   Kalyan      51       63     62     93
5    105  Karthik      48       62     39     68
6    106   Kambli      53       81     59     92
7    107  Praveen      46       88     74     86
8    108   Ganesh      53       62     76     88
9    109     Nags      55       77     44     77
10   110    Biswa      66       48     86     95
11   111   Ritchi      66       68     64     76
12   104   Kalyan      51       63     62     93
13   112  shareef      50       63     99     90
14   113     sonu      60       89     98     87
15   114   Rajesh      45       67     77     55
16   115   Rakesh      67       78     88     78

In [24]:
a.iloc[:,0:6]

    htno     name  telugu  english  hindi  maths
0    100   Ramesh      50       60     66     98
1    101   Rajesh      45       67     34     67
2    102   Rossum      56       88     56     99
3    103     Raji      56       78     34     56
4    104   Kalyan      51       63     62     93
5    105  Karthik      48       62     39     68
6    106   Kambli      53       81     59     92
7    107  Praveen      46       88     74     86
8    108   Ganesh      53       62     76     88
9    109     Nags      55       77     44     77
10   110    Biswa      66       48     86     95
11   111   Ritchi      66       68     64     76
12   104   Kalyan      51       63     62     93
13   112  shareef      50       63     99     90
14   113     sonu      60       89     98     87
15   114   Rajesh      45       67     77     55
16   115   Rakesh      67       78     88     78