In [2]:
#Create the DataFrame Object with "peoples.csv" File
import numpy as np
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\peoples.csv")
print(a)

    CID        NAME STATE DSG
0   100    VISHNAVI    TS  SE
1   200     MANJULA    AP  SE
2   300     BHUMIKA    TS  TL
3   400  LAXIMIDEVI  BANG  TL
4   500       SWATI    AP  PM
5   600     SHAKSHI  BANG  PM
6   700    BHARGAVI    TS  SE
7   800       UDAYA    AP  PM
8   900       SWETA  BANG  SE
9   750      ANJALI    AP  TL
10  650    JAYASREE  BANG  PM
11  550     SIRISHA    AP  HR
12  450     MADHAVI    TS  HR
13  350      AKHILA    AP  HR
14  150       RADHA  BANG  TL
15  950     MOUNIKA    AP  HR
16  125     FARHANA    TS  TL
17  185      JHANSI    AP  TL

In [3]:
#Get State-wise Groups
b=a.groupby("STATE")
print(type(b))

<class 'pandas.api.typing.DataFrameGroupBy'>

In [4]:
#Get the Group-Wise Data
for gname,gdata in b:
    print("Group Name:",gname)
    print(gdata)

Group Name: AP
    CID     NAME STATE DSG
1   200  MANJULA    AP  SE
4   500    SWATI    AP  PM
7   800    UDAYA    AP  PM
9   750   ANJALI    AP  TL
11  550  SIRISHA    AP  HR
13  350   AKHILA    AP  HR
15  950  MOUNIKA    AP  HR
17  185   JHANSI    AP  TL
Group Name: BANG
    CID        NAME STATE DSG
3   400  LAXIMIDEVI  BANG  TL
5   600     SHAKSHI  BANG  PM
8   900       SWETA  BANG  SE
10  650    JAYASREE  BANG  PM
14  150       RADHA  BANG  TL
Group Name: TS
    CID      NAME STATE DSG
0   100  VISHNAVI    TS  SE
2   300   BHUMIKA    TS  TL
6   700  BHARGAVI    TS  SE
12  450   MADHAVI    TS  HR
16  125   FARHANA    TS  TL

In [5]:
#Get the Group-Wise Data Based State
for gname,gdata in a.groupby("STATE"):
    print("Group Name:",gname)
    print(gdata)

Group Name: AP
    CID     NAME STATE DSG
1   200  MANJULA    AP  SE
4   500    SWATI    AP  PM
7   800    UDAYA    AP  PM
9   750   ANJALI    AP  TL
11  550  SIRISHA    AP  HR
13  350   AKHILA    AP  HR
15  950  MOUNIKA    AP  HR
17  185   JHANSI    AP  TL
Group Name: BANG
    CID        NAME STATE DSG
3   400  LAXIMIDEVI  BANG  TL
5   600     SHAKSHI  BANG  PM
8   900       SWETA  BANG  SE
10  650    JAYASREE  BANG  PM
14  150       RADHA  BANG  TL
Group Name: TS
    CID      NAME STATE DSG
0   100  VISHNAVI    TS  SE
2   300   BHUMIKA    TS  TL
6   700  BHARGAVI    TS  SE
12  450   MADHAVI    TS  HR
16  125   FARHANA    TS  TL

In [6]:
#Get the Group-Wise Data Based  on DSG
for gname,gdata in a.groupby("DSG"):
    print("Group Name:",gname)
    print(gdata)

Group Name: HR
    CID     NAME STATE DSG
11  550  SIRISHA    AP  HR
12  450  MADHAVI    TS  HR
13  350   AKHILA    AP  HR
15  950  MOUNIKA    AP  HR
Group Name: PM
    CID      NAME STATE DSG
4   500     SWATI    AP  PM
5   600   SHAKSHI  BANG  PM
7   800     UDAYA    AP  PM
10  650  JAYASREE  BANG  PM
Group Name: SE
   CID      NAME STATE DSG
0  100  VISHNAVI    TS  SE
1  200   MANJULA    AP  SE
6  700  BHARGAVI    TS  SE
8  900     SWETA  BANG  SE
Group Name: TL
    CID        NAME STATE DSG
2   300     BHUMIKA    TS  TL
3   400  LAXIMIDEVI  BANG  TL
9   750      ANJALI    AP  TL
14  150       RADHA  BANG  TL
16  125     FARHANA    TS  TL
17  185      JHANSI    AP  TL

In [7]:
b=a.groupby("DSG")
b.first()

     CID      NAME STATE
DSG
HR   550   SIRISHA    AP
PM   500     SWATI    AP
SE   100  VISHNAVI    TS
TL   300   BHUMIKA    TS

In [8]:
#Last Records from Each Group
b.last()

     CID      NAME STATE
DSG
HR   950   MOUNIKA    AP
PM   650  JAYASREE  BANG
SE   900     SWETA  BANG
TL   185    JHANSI    AP

In [11]:
#Get 3d Record Values from Each group
b.nth(2)

    CID      NAME STATE DSG
6   700  BHARGAVI    TS  SE
7   800     UDAYA    AP  PM
9   750    ANJALI    AP  TL
13  350    AKHILA    AP  HR

In [12]:
a.groupby("DSG").size()

DSG
HR    4
PM    4
SE    4
TL    6
dtype: int64

In [13]:
a.groupby("STATE").size()

STATE
AP      8
BANG    5
TS      5
dtype: int64

In [14]:
a.groupby("STATE").count()

       CID  NAME  DSG
STATE
AP       8     8    8
BANG     5     5    5
TS       5     5    5

In [15]:
#Create the DataFrame Object with "population.csv" File
import numpy as np
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\population.csv")
print(a)

   ID     Name  Age    City  Experience
0  11     Jack   44  Sydney          19
1  12     Riti   41   Delhi          17
2  13     Aadi   46  Mumbai          11
3  14    Mohit   45   Delhi          15
4  15    Veena   43   Delhi          14
5  16  Shaunak   42  Mumbai          17
6  17    Manik   42  Sydney          14
7  18    Vikas   42   Delhi          11
8  19    Samir   42  Mumbai          15
9  20  Shobhit   40  Sydney          12

In [17]:
#Get City Based Group Data
for gn,ginfo in a.groupby("City"):
    print("Group Name:",gn)
    print(ginfo)

Group Name: Delhi
   ID   Name  Age   City  Experience
1  12   Riti   41  Delhi          17
3  14  Mohit   45  Delhi          15
4  15  Veena   43  Delhi          14
7  18  Vikas   42  Delhi          11
Group Name: Mumbai
   ID     Name  Age    City  Experience
2  13     Aadi   46  Mumbai          11
5  16  Shaunak   42  Mumbai          17
8  19    Samir   42  Mumbai          15
Group Name: Sydney
   ID     Name  Age    City  Experience
0  11     Jack   44  Sydney          19
6  17    Manik   42  Sydney          14
9  20  Shobhit   40  Sydney          12

In [18]:
a.groupby("City").size()

City
Delhi     4
Mumbai    3
Sydney    3
dtype: int64

In [19]:
a.groupby("City")["Age"].mean()

City
Delhi     42.750000
Mumbai    43.333333
Sydney    42.000000
Name: Age, dtype: float64

In [20]:
a.groupby("City")["Experience"].mean()

City
Delhi     14.250000
Mumbai    14.333333
Sydney    15.000000
Name: Experience, dtype: float64

In [21]:
a.groupby("City")["Experience"].max()

City
Delhi     17
Mumbai    17
Sydney    19
Name: Experience, dtype: int64

In [23]:
a.groupby("City")["Experience"].min()

City
Delhi     11
Mumbai    11
Sydney    12
Name: Experience, dtype: int64

In [25]:
import pandas as pd
data={ 'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vijay'],
		'Department': ['IT', 'HR', 'IT', 'HR', 'IT'],
		'Salary': [50000, 40000, 60000, 45000, 70000]
     }
a=pd.DataFrame(data)
print(a)

    Name Department  Salary
0   Amit         IT   50000
1  Priya         HR   40000
2  Rahul         IT   60000
3  Sneha         HR   45000
4  Vijay         IT   70000

In [26]:
#Calculate the average salary of each department.
for gn,gf in a.groupby("Department"):
    print("Group Name:",gn)
    print(gf)

Group Name: HR
    Name Department  Salary
1  Priya         HR   40000
3  Sneha         HR   45000
Group Name: IT
    Name Department  Salary
0   Amit         IT   50000
2  Rahul         IT   60000
4  Vijay         IT   70000

In [27]:
#Calculate the average salary of each department.
a.groupby("Department")["Salary"].mean()

Department
HR    42500.0
IT    60000.0
Name: Salary, dtype: float64

In [28]:
#Calculate the Total salary of each department.
a.groupby("Department")["Salary"].sum()

Department
HR     85000
IT    180000
Name: Salary, dtype: int64

In [29]:
#calculate the Number of  departments.
a.groupby("Department").count()

            Name  Salary
Department
HR             2       2
IT             3       3

In [30]:
#Calculate the Number of  departments.
a.groupby("Department").size()

Department
HR    2
IT    3
dtype: int64

In [31]:
#calculate the Max salary of each department.
a.groupby("Department")["Salary"].max()

Department
HR    45000
IT    70000
Name: Salary, dtype: int64

In [32]:
#Calculate the Max salary of each department.
a.groupby("Department")["Salary"].min()

Department
HR    40000
IT    50000
Name: Salary, dtype: int64

In [33]:
#Grouping By Multiple Columns

In [34]:
import pandas as pd
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'IT'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Salary': [50000, 60000, 40000, 45000, 70000]
}

a= pd.DataFrame(data)
print(a)

  Department  Gender  Salary
0         IT    Male   50000
1         IT  Female   60000
2         HR    Male   40000
3         HR  Female   45000
4         IT    Male   70000

In [35]:
for gn,gf in a.groupby(["Department","Gender"]):
    print("Group Name:",gn)
    print(gf)

Group Name: ('HR', 'Female')
  Department  Gender  Salary
3         HR  Female   45000
Group Name: ('HR', 'Male')
  Department Gender  Salary
2         HR   Male   40000
Group Name: ('IT', 'Female')
  Department  Gender  Salary
1         IT  Female   60000
Group Name: ('IT', 'Male')
  Department Gender  Salary
0         IT   Male   50000
4         IT   Male   70000

In [36]:
for mg,gf in a.groupby(['Department', 'Gender']):
    print("{}-{}".format(mg[0],mg[1]))
    print(gf)

HR-Female
  Department  Gender  Salary
3         HR  Female   45000
HR-Male
  Department Gender  Salary
2         HR   Male   40000
IT-Female
  Department  Gender  Salary
1         IT  Female   60000
IT-Male
  Department Gender  Salary
0         IT   Male   50000
4         IT   Male   70000

In [37]:
#calculate the average salary for each department and gender combination.
a.groupby(["Department","Gender"])["Salary"].mean()

Department  Gender
HR          Female    45000.0
            Male      40000.0
IT          Female    60000.0
            Male      60000.0
Name: Salary, dtype: float64

In [39]:
# Using Multiple Aggregations with agg()
result=a.groupby("Department")["Salary"].agg(["sum","mean","max","min","count"])
print(result)

               sum     mean    max    min  count
Department
HR           85000  42500.0  45000  40000      2
IT          180000  60000.0  70000  50000      3

In [40]:
import pandas as pd
data = {
    'Student': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vijay'],
    'Course': ['Python', 'Java', 'Python', 'Python', 'Java']
}
a= pd.DataFrame(data)
print(a)

  Student  Course
0    Amit  Python
1   Priya    Java
2   Rahul  Python
3   Sneha  Python
4   Vijay    Java

In [42]:
#Count the students in each course
for gn,gf in a.groupby("Course"):
    print("Group Name:",gn)
    print(gf)
    print("--------------------------")

Group Name: Java
  Student Course
1   Priya   Java
4   Vijay   Java
--------------------------
Group Name: Python
  Student  Course
0    Amit  Python
2   Rahul  Python
3   Sneha  Python
--------------------------

In [44]:
#Count the students in each course
a.groupby("Course")["Student"].count()

Course
Java      2
Python    3
Name: Student, dtype: int64

In [45]:
import pandas as pd
data = {
    'City': ['Hyderabad', 'Chennai', 'Hyderabad', 'Mumbai', 'Chennai'],
    'Sales': [1000, 2000, 1500, 3000, 2500]
}
a=pd.DataFrame(data)
print(a)

        City  Sales
0  Hyderabad   1000
1    Chennai   2000
2  Hyderabad   1500
3     Mumbai   3000
4    Chennai   2500

In [46]:
for gn,gf in a.groupby("City"):
    print("Group Name:",gn)
    print(gf)

Group Name: Chennai
      City  Sales
1  Chennai   2000
4  Chennai   2500
Group Name: Hyderabad
        City  Sales
0  Hyderabad   1000
2  Hyderabad   1500
Group Name: Mumbai
     City  Sales
3  Mumbai   3000

In [47]:
#Calculate the total sales for each city.
a.groupby("City")["Sales"].sum()

City
Chennai      4500
Hyderabad    2500
Mumbai       3000
Name: Sales, dtype: int64

In [48]:
#Calculate the average sales for each city.
a.groupby("City")["Sales"].mean()

City
Chennai      2250.0
Hyderabad    1250.0
Mumbai       3000.0
Name: Sales, dtype: float64

In [49]:
#Find the maximum sales for each city.
a.groupby("City")["Sales"].max()

City
Chennai      2500
Hyderabad    1500
Mumbai       3000
Name: Sales, dtype: int64

In [50]:
#Count the number of records for each city.
a.groupby("City").size()

City
Chennai      2
Hyderabad    2
Mumbai       1
dtype: int64

In [51]:
#Calculate the total and average sales together using agg().
a.groupby("City")["Sales"].agg(["sum","mean","max","min"])

            sum    mean   max   min
City
Chennai    4500  2250.0  2500  2000
Hyderabad  2500  1250.0  1500  1000
Mumbai     3000  3000.0  3000  3000

In [52]:
values=a.groupby("City").agg({"Sales":"mean"})
print(values)

            Sales
City
Chennai    2250.0
Hyderabad  1250.0
Mumbai     3000.0

In [53]:
#Create the DataFrame Object with "population.csv" File
import numpy as np
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\population.csv")
print(a)

   ID     Name  Age    City  Experience
0  11     Jack   44  Sydney          19
1  12     Riti   41   Delhi          17
2  13     Aadi   46  Mumbai          11
3  14    Mohit   45   Delhi          15
4  15    Veena   43   Delhi          14
5  16  Shaunak   42  Mumbai          17
6  17    Manik   42  Sydney          14
7  18    Vikas   42   Delhi          11
8  19    Samir   42  Mumbai          15
9  20  Shobhit   40  Sydney          12

In [54]:
# Get the mean Age column values in each group and 
# Sum of Experience column values in each group
values=a.groupby("City").agg({"Age":"mean","Experience":"sum"})
print(values)

              Age  Experience
City
Delhi   42.750000          57
Mumbai  43.333333          43
Sydney  42.000000          45