In [1]:
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [2]:
#Get 15 Record details
a.loc[15]

htno          114
name       Rajesh
telugu         45
english        67
hindi          77
maths          55
science        66
social         46
Name: 15, dtype: object

In [3]:
a.loc[14]

htno        113
name       sonu
telugu       60
english      89
hindi        98
maths        87
science      77
social       68
Name: 14, dtype: object

In [4]:
#Get the name of student from 15th record 
a.loc[15,["name"]]

name    Rajesh
Name: 15, dtype: str

In [5]:
a[15:16]["name"]

15    Rajesh
Name: name, dtype: str

In [6]:
a["name"][15:16]

15    Rajesh
Name: name, dtype: str

In [7]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [8]:
#Get Name, Maths and Science Details of 15th Record
a.loc[15,["name","maths","science"]]

name       Rajesh
maths          55
science        66
Name: 15, dtype: object

In [11]:
a[15:16][["name","maths","science"]]

      name  maths  science
15  Rajesh     55       66

In [12]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [13]:
#Get Names of 10 to 15 Records
a.loc[10:15,["name"]]

       name
10    Biswa
11   Ritchi
12   Kalyan
13  shareef
14     sonu
15   Rajesh

In [15]:
#Get Names of Last 5 Records
a.loc[a.shape[0]-5:,["name"]]

       name
12   Kalyan
13  shareef
14     sonu
15   Rajesh
16   Rakesh

In [16]:
#Get htno,Names,social  of Last 5 Records
a.loc[a.shape[0]-5:,["htno","name","social"]]

    htno     name  social
12   104   Kalyan      51
13   112  shareef      67
14   113     sonu      68
15   114   Rajesh      46
16   115   Rakesh      49

In [17]:
#Get htno,Names,social  of Last 2 Records
a.loc[a.shape[0]-2:,["htno","name","social"]]

    htno    name  social
15   114  Rajesh      46
16   115  Rakesh      49

In [18]:
#Get the Colnames from htno to science
a[["htno","name","telugu","english","hindi","maths","science"]]

    htno     name  telugu  english  hindi  maths  science
0    100   Ramesh      50       60     66     98       66
1    101   Rajesh      45       67     34     67       66
2    102   Rossum      56       88     56     99       44
3    103     Raji      56       78     34     56       88
4    104   Kalyan      51       63     62     93       67
5    105  Karthik      48       62     39     68       65
6    106   Kambli      53       81     59     92       48
7    107  Praveen      46       88     74     86       78
8    108   Ganesh      53       62     76     88       76
9    109     Nags      55       77     44     77       86
10   110    Biswa      66       48     86     95       48
11   111   Ritchi      66       68     64     76       98
12   104   Kalyan      51       63     62     93       67
13   112  shareef      50       63     99     90       76
14   113     sonu      60       89     98     87       77
15   114   Rajesh      45       67     77     55       66
16   115   Rakesh      67       78     88     78       67

In [19]:
#Get the Colnames from htno to science  by using Slicing
a.loc["htno":"science"]

Empty DataFrame
Columns: [htno, name, telugu, english, hindi, maths, science, social]
Index: []

In [20]:
#Get the Records details for Colnames from htno to science  by using Slicing
a.loc[::,"htno":"science"]

    htno     name  telugu  english  hindi  maths  science
0    100   Ramesh      50       60     66     98       66
1    101   Rajesh      45       67     34     67       66
2    102   Rossum      56       88     56     99       44
3    103     Raji      56       78     34     56       88
4    104   Kalyan      51       63     62     93       67
5    105  Karthik      48       62     39     68       65
6    106   Kambli      53       81     59     92       48
7    107  Praveen      46       88     74     86       78
8    108   Ganesh      53       62     76     88       76
9    109     Nags      55       77     44     77       86
10   110    Biswa      66       48     86     95       48
11   111   Ritchi      66       68     64     76       98
12   104   Kalyan      51       63     62     93       67
13   112  shareef      50       63     99     90       76
14   113     sonu      60       89     98     87       77
15   114   Rajesh      45       67     77     55       66
16   115   Rakesh      67       78     88     78       67

In [21]:
#Get 15 Records Details from HTNO to Science
a.loc[15,"htno":"science"]

htno          114
name       Rajesh
telugu         45
english        67
hindi          77
maths          55
science        66
Name: 15, dtype: object

In [22]:
#Get 15 Records Details from HTNO to Science
a.loc[15:15,"htno":"science"]

    htno    name  telugu  english  hindi  maths  science
15   114  Rajesh      45       67     77     55       66