In [7]:
#Create an Object of DataFrame
import numpy as np
import pandas as pd
d={"FirstScore":[100,90,np.nan,95],
   "SecondScore":[90,np.nan,98,89],
   "ThirdScore":[np.nan,50,60,70]}
a=pd.DataFrame(d)
print(a,type(a))

   FirstScore  SecondScore  ThirdScore
0       100.0         90.0         NaN
1        90.0          NaN        50.0
2         NaN         98.0        60.0
3        95.0         89.0        70.0 <class 'pandas.DataFrame'>

In [8]:
#Create an Object of DataFrame
import numpy as np
import pandas as pd
d={"Courses":["Spark","Java","Scala","Python"],
   "Fees":[20000,np.nan,26000,24000],
   "Duration":["30Days","40Days",pd.NA,"40Days"],
   "Discount":[1000,np.nan,2500,None]}
b=pd.DataFrame(d)
print(b,type(b))

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      NaN   40Days       NaN
2   Scala  26000.0      NaN    2500.0
3  Python  24000.0   40Days       NaN <class 'pandas.DataFrame'>

In [9]:
#Find the Missing
a.isna()

   FirstScore  SecondScore  ThirdScore
0       False        False        True
1       False         True       False
2        True        False       False
3       False        False       False

In [10]:
a[a.isna()]

   FirstScore  SecondScore  ThirdScore
0         NaN          NaN         NaN
1         NaN          NaN         NaN
2         NaN          NaN         NaN
3         NaN          NaN         NaN

In [11]:
a.isna().sum()

FirstScore     1
SecondScore    1
ThirdScore     1
dtype: int64

In [12]:
a.isnull()

   FirstScore  SecondScore  ThirdScore
0       False        False        True
1       False         True       False
2        True        False       False
3       False        False       False

In [13]:
a.isnull().sum()

FirstScore     1
SecondScore    1
ThirdScore     1
dtype: int64

In [14]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      NaN   40Days       NaN
2   Scala  26000.0      NaN    2500.0
3  Python  24000.0   40Days       NaN

In [15]:
b.isna()

   Courses   Fees  Duration  Discount
0    False  False     False     False
1    False   True     False      True
2    False  False      True     False
3    False  False     False      True

In [16]:
b.isna().sum()

Courses     0
Fees        1
Duration    1
Discount    2
dtype: int64

In [17]:
print(a)

   FirstScore  SecondScore  ThirdScore
0       100.0         90.0         NaN
1        90.0          NaN        50.0
2         NaN         98.0        60.0
3        95.0         89.0        70.0

In [20]:
#Fill all Missing Values with a Common Value on Programmer Choice
a.fillna(0)

   FirstScore  SecondScore  ThirdScore
0       100.0         90.0         0.0
1        90.0          0.0        50.0
2         0.0         98.0        60.0
3        95.0         89.0        70.0

In [21]:
print(a)

   FirstScore  SecondScore  ThirdScore
0       100.0         90.0         NaN
1        90.0          NaN        50.0
2         NaN         98.0        60.0
3        95.0         89.0        70.0

In [23]:
#Fill all Missing Values with a Common Value on Programmer Choice
a.fillna(0,inplace=True)
print(a)

   FirstScore  SecondScore  ThirdScore
0       100.0         90.0         0.0
1        90.0          0.0        50.0
2         0.0         98.0        60.0
3        95.0         89.0        70.0

In [24]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      NaN   40Days       NaN
2   Scala  26000.0      NaN    2500.0
3  Python  24000.0   40Days       NaN

In [25]:
b.fillna(0)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      0.0   40Days       0.0
2   Scala  26000.0        0    2500.0
3  Python  24000.0   40Days       0.0

In [26]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      NaN   40Days       NaN
2   Scala  26000.0      NaN    2500.0
3  Python  24000.0   40Days       NaN

In [29]:
b["Fees"]=b["Fees"].fillna(10000)

In [30]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      0.0   40Days       NaN
2   Scala  26000.0      NaN    2500.0
3  Python  24000.0   40Days       NaN

In [32]:
b["Duration"]=b["Duration"].fillna("25Days")

In [33]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      0.0   40Days       NaN
2   Scala  26000.0   25Days    2500.0
3  Python  24000.0   40Days       NaN

In [34]:
b["Discount"]=b["Discount"].fillna(1000)

In [35]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      0.0   40Days    1000.0
2   Scala  26000.0   25Days    2500.0
3  Python  24000.0   40Days    1000.0

In [36]:
b.loc[b["Courses"]=="Python",["Discount"]]=500

In [37]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   30Days    1000.0
1    Java      0.0   40Days    1000.0
2   Scala  26000.0   25Days    2500.0
3  Python  24000.0   40Days     500.0

In [38]:
b.loc[b["Courses"]=="Spark",["Duration"]]="35Days"

In [39]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   35Days    1000.0
1    Java      0.0   40Days    1000.0
2   Scala  26000.0   25Days    2500.0
3  Python  24000.0   40Days     500.0

In [40]:
b.loc[b["Courses"]=="Scala",["Duration"]]="30Days"

In [41]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   35Days    1000.0
1    Java      0.0   40Days    1000.0
2   Scala  26000.0   30Days    2500.0
3  Python  24000.0   40Days     500.0

In [42]:
b.loc[b["Courses"]=="Java",["Fees"]]=30000

In [43]:
print(b)

  Courses     Fees Duration  Discount
0   Spark  20000.0   35Days    1000.0
1    Java  30000.0   40Days    1000.0
2   Scala  26000.0   30Days    2500.0
3  Python  24000.0   40Days     500.0