In [2]:
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [4]:
a["total"]=a["telugu"]+a["english"]+a["hindi"]+a["maths"]+a["science"]+a["social"]
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

In [5]:
import numpy as np
a["percent"]=np.around((a["total"]/600)*100,2)
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent
0     65.83
1     59.50
2     70.00
3     61.17
4     64.50
5     61.67
6     67.67
7     69.50
8     65.00
9     66.17
10    65.00
11    74.50
12    64.50
13    74.17
14    79.83
15    59.33
16    71.17

In [6]:
#Sort the DataFrame Data Based on Col Name---percent
a.sort_values(["percent"])

,htno,name,telugu,english,hindi,maths,science,social,total,percent
15,114,Rajesh,45,67,77,55,66,46,356,59.33
1,101,Rajesh,45,67,34,67,66,78,357,59.50
3,103,Raji,56,78,34,56,88,55,367,61.17
5,105,Karthik,48,62,39,68,65,88,370,61.67
12,104,Kalyan,51,63,62,93,67,51,387,64.50
4,104,Kalyan,51,63,62,93,67,51,387,64.50
10,110,Biswa,66,48,86,95,48,47,390,65.00
8,108,Ganesh,53,62,76,88,76,35,390,65.00
0,100,Ramesh,50,60,66,98,66,55,395,65.83
9,109,Nags,55,77,44,77,86,58,397,66.17
6,106,Kambli,53,81,59,92,48,73,406,67.67
7,107,Praveen,46,88,74,86,78,45,417,69.50
2,102,Rossum,56,88,56,99,44,77,420,70.00
16,115,Rakesh,67,78,88,78,67,49,427,71.17
13,112,shareef,50,63,99,90,76,67,445,74.17
11,111,Ritchi,66,68,64,76,98,75,447,74.50
14,113,sonu,60,89,98,87,77,68,479,79.83

In [7]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
0    100   Ramesh      50       60     66     98       66      55    395
1    101   Rajesh      45       67     34     67       66      78    357
2    102   Rossum      56       88     56     99       44      77    420
3    103     Raji      56       78     34     56       88      55    367
4    104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
8    108   Ganesh      53       62     76     88       76      35    390
9    109     Nags      55       77     44     77       86      58    397
10   110    Biswa      66       48     86     95       48      47    390
11   111   Ritchi      66       68     64     76       98      75    447
12   104   Kalyan      51       63     62     93       67      51    387
13   112  shareef      50       63     99     90       76      67    445
14   113     sonu      60       89     98     87       77      68    479
15   114   Rajesh      45       67     77     55       66      46    356
16   115   Rakesh      67       78     88     78       67      49    427

    percent
0     65.83
1     59.50
2     70.00
3     61.17
4     64.50
5     61.67
6     67.67
7     69.50
8     65.00
9     66.17
10    65.00
11    74.50
12    64.50
13    74.17
14    79.83
15    59.33
16    71.17

In [9]:
#Sort the DataFrame Data Based on Column Name---percent
a.sort_values(["percent"],inplace=True)
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
15   114   Rajesh      45       67     77     55       66      46    356
1    101   Rajesh      45       67     34     67       66      78    357
3    103     Raji      56       78     34     56       88      55    367
5    105  Karthik      48       62     39     68       65      88    370
12   104   Kalyan      51       63     62     93       67      51    387
4    104   Kalyan      51       63     62     93       67      51    387
10   110    Biswa      66       48     86     95       48      47    390
8    108   Ganesh      53       62     76     88       76      35    390
0    100   Ramesh      50       60     66     98       66      55    395
9    109     Nags      55       77     44     77       86      58    397
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
2    102   Rossum      56       88     56     99       44      77    420
16   115   Rakesh      67       78     88     78       67      49    427
13   112  shareef      50       63     99     90       76      67    445
11   111   Ritchi      66       68     64     76       98      75    447
14   113     sonu      60       89     98     87       77      68    479

    percent
15    59.33
1     59.50
3     61.17
5     61.67
12    64.50
4     64.50
10    65.00
8     65.00
0     65.83
9     66.17
6     67.67
7     69.50
2     70.00
16    71.17
13    74.17
11    74.50
14    79.83

In [10]:
#Finding the highest percentage present 
a["percent"].tail(1).values[0]

np.float64(79.83)

In [11]:
a["percent"]==a["percent"].tail(1).values[0]

15    False
1     False
3     False
5     False
12    False
4     False
10    False
8     False
0     False
9     False
6     False
7     False
2     False
16    False
13    False
11    False
14     True
Name: percent, dtype: bool

In [12]:
a.loc[a["percent"]==a["percent"].tail(1).values[0]]

    htno  name  telugu  english  hindi  maths  science  social  total  percent
14   113  sonu      60       89     98     87       77      68    479    79.83

In [14]:
a.loc[a["percent"]==a["percent"].tail(1).values[0]]["name"]

14    sonu
Name: name, dtype: str

In [16]:
a.loc[a["percent"]==a["percent"].tail(1).values[0]]["name"].values

<ArrowStringArray>
['sonu']
Length: 1, dtype: str

In [17]:
a.loc[a["percent"]==a["percent"].tail(1).values[0]]["name"].values[0]

'sonu'

In [18]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
15   114   Rajesh      45       67     77     55       66      46    356
1    101   Rajesh      45       67     34     67       66      78    357
3    103     Raji      56       78     34     56       88      55    367
5    105  Karthik      48       62     39     68       65      88    370
12   104   Kalyan      51       63     62     93       67      51    387
4    104   Kalyan      51       63     62     93       67      51    387
10   110    Biswa      66       48     86     95       48      47    390
8    108   Ganesh      53       62     76     88       76      35    390
0    100   Ramesh      50       60     66     98       66      55    395
9    109     Nags      55       77     44     77       86      58    397
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
2    102   Rossum      56       88     56     99       44      77    420
16   115   Rakesh      67       78     88     78       67      49    427
13   112  shareef      50       63     99     90       76      67    445
11   111   Ritchi      66       68     64     76       98      75    447
14   113     sonu      60       89     98     87       77      68    479

    percent
15    59.33
1     59.50
3     61.17
5     61.67
12    64.50
4     64.50
10    65.00
8     65.00
0     65.83
9     66.17
6     67.67
7     69.50
2     70.00
16    71.17
13    74.17
11    74.50
14    79.83

In [20]:
#Get the DataFrame Data into Decending Order
a.sort_values(["percent"],ascending=False)

,htno,name,telugu,english,hindi,maths,science,social,total,percent
14,113,sonu,60,89,98,87,77,68,479,79.83
11,111,Ritchi,66,68,64,76,98,75,447,74.50
13,112,shareef,50,63,99,90,76,67,445,74.17
16,115,Rakesh,67,78,88,78,67,49,427,71.17
2,102,Rossum,56,88,56,99,44,77,420,70.00
7,107,Praveen,46,88,74,86,78,45,417,69.50
6,106,Kambli,53,81,59,92,48,73,406,67.67
9,109,Nags,55,77,44,77,86,58,397,66.17
0,100,Ramesh,50,60,66,98,66,55,395,65.83
8,108,Ganesh,53,62,76,88,76,35,390,65.00
10,110,Biswa,66,48,86,95,48,47,390,65.00
4,104,Kalyan,51,63,62,93,67,51,387,64.50
12,104,Kalyan,51,63,62,93,67,51,387,64.50
5,105,Karthik,48,62,39,68,65,88,370,61.67
3,103,Raji,56,78,34,56,88,55,367,61.17
1,101,Rajesh,45,67,34,67,66,78,357,59.50
15,114,Rajesh,45,67,77,55,66,46,356,59.33

In [21]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
15   114   Rajesh      45       67     77     55       66      46    356
1    101   Rajesh      45       67     34     67       66      78    357
3    103     Raji      56       78     34     56       88      55    367
5    105  Karthik      48       62     39     68       65      88    370
12   104   Kalyan      51       63     62     93       67      51    387
4    104   Kalyan      51       63     62     93       67      51    387
10   110    Biswa      66       48     86     95       48      47    390
8    108   Ganesh      53       62     76     88       76      35    390
0    100   Ramesh      50       60     66     98       66      55    395
9    109     Nags      55       77     44     77       86      58    397
6    106   Kambli      53       81     59     92       48      73    406
7    107  Praveen      46       88     74     86       78      45    417
2    102   Rossum      56       88     56     99       44      77    420
16   115   Rakesh      67       78     88     78       67      49    427
13   112  shareef      50       63     99     90       76      67    445
11   111   Ritchi      66       68     64     76       98      75    447
14   113     sonu      60       89     98     87       77      68    479

    percent
15    59.33
1     59.50
3     61.17
5     61.67
12    64.50
4     64.50
10    65.00
8     65.00
0     65.83
9     66.17
6     67.67
7     69.50
2     70.00
16    71.17
13    74.17
11    74.50
14    79.83

In [23]:
#Get the DataFrame Data into Decending Order
a.sort_values(["percent"],ascending=False,inplace=True)
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
14   113     sonu      60       89     98     87       77      68    479
11   111   Ritchi      66       68     64     76       98      75    447
13   112  shareef      50       63     99     90       76      67    445
16   115   Rakesh      67       78     88     78       67      49    427
2    102   Rossum      56       88     56     99       44      77    420
7    107  Praveen      46       88     74     86       78      45    417
6    106   Kambli      53       81     59     92       48      73    406
9    109     Nags      55       77     44     77       86      58    397
0    100   Ramesh      50       60     66     98       66      55    395
8    108   Ganesh      53       62     76     88       76      35    390
10   110    Biswa      66       48     86     95       48      47    390
4    104   Kalyan      51       63     62     93       67      51    387
12   104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
3    103     Raji      56       78     34     56       88      55    367
1    101   Rajesh      45       67     34     67       66      78    357
15   114   Rajesh      45       67     77     55       66      46    356

    percent
14    79.83
11    74.50
13    74.17
16    71.17
2     70.00
7     69.50
6     67.67
9     66.17
0     65.83
8     65.00
10    65.00
4     64.50
12    64.50
5     61.67
3     61.17
1     59.50
15    59.33

In [24]:
a["percent"].values[0]

np.float64(79.83)

In [25]:
a["percent"]==a["percent"].values[0]

14     True
11    False
13    False
16    False
2     False
7     False
6     False
9     False
0     False
8     False
10    False
4     False
12    False
5     False
3     False
1     False
15    False
Name: percent, dtype: bool

In [26]:
a.loc[a["percent"]==a["percent"].values[0]]

    htno  name  telugu  english  hindi  maths  science  social  total  percent
14   113  sonu      60       89     98     87       77      68    479    79.83

In [28]:
a.loc[a["percent"]==a["percent"].values[0]][["name","percent"]]

    name  percent
14  sonu    79.83

In [29]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total  \
14   113     sonu      60       89     98     87       77      68    479
11   111   Ritchi      66       68     64     76       98      75    447
13   112  shareef      50       63     99     90       76      67    445
16   115   Rakesh      67       78     88     78       67      49    427
2    102   Rossum      56       88     56     99       44      77    420
7    107  Praveen      46       88     74     86       78      45    417
6    106   Kambli      53       81     59     92       48      73    406
9    109     Nags      55       77     44     77       86      58    397
0    100   Ramesh      50       60     66     98       66      55    395
8    108   Ganesh      53       62     76     88       76      35    390
10   110    Biswa      66       48     86     95       48      47    390
4    104   Kalyan      51       63     62     93       67      51    387
12   104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
3    103     Raji      56       78     34     56       88      55    367
1    101   Rajesh      45       67     34     67       66      78    357
15   114   Rajesh      45       67     77     55       66      46    356

    percent
14    79.83
11    74.50
13    74.17
16    71.17
2     70.00
7     69.50
6     67.67
9     66.17
0     65.83
8     65.00
10    65.00
4     64.50
12    64.50
5     61.67
3     61.17
1     59.50
15    59.33

In [42]:
print(a.columns)

Index(['htno', 'name', 'telugu', 'english', 'hindi', 'maths', 'science',
       'social', 'total'],
      dtype='str')

In [43]:
#Remove the Col Name --percent
#a.drop(columns="percent",inplace=True)

In [44]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total
14   113     sonu      60       89     98     87       77      68    479
11   111   Ritchi      66       68     64     76       98      75    447
13   112  shareef      50       63     99     90       76      67    445
16   115   Rakesh      67       78     88     78       67      49    427
2    102   Rossum      56       88     56     99       44      77    420
7    107  Praveen      46       88     74     86       78      45    417
6    106   Kambli      53       81     59     92       48      73    406
9    109     Nags      55       77     44     77       86      58    397
0    100   Ramesh      50       60     66     98       66      55    395
8    108   Ganesh      53       62     76     88       76      35    390
10   110    Biswa      66       48     86     95       48      47    390
4    104   Kalyan      51       63     62     93       67      51    387
12   104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
3    103     Raji      56       78     34     56       88      55    367
1    101   Rajesh      45       67     34     67       66      78    357
15   114   Rajesh      45       67     77     55       66      46    356

In [45]:
#Remove Multiple Column Names from DataFrame
a.drop(columns=["maths","total"])

    htno     name  telugu  english  hindi  science  social
14   113     sonu      60       89     98       77      68
11   111   Ritchi      66       68     64       98      75
13   112  shareef      50       63     99       76      67
16   115   Rakesh      67       78     88       67      49
2    102   Rossum      56       88     56       44      77
7    107  Praveen      46       88     74       78      45
6    106   Kambli      53       81     59       48      73
9    109     Nags      55       77     44       86      58
0    100   Ramesh      50       60     66       66      55
8    108   Ganesh      53       62     76       76      35
10   110    Biswa      66       48     86       48      47
4    104   Kalyan      51       63     62       67      51
12   104   Kalyan      51       63     62       67      51
5    105  Karthik      48       62     39       65      88
3    103     Raji      56       78     34       88      55
1    101   Rajesh      45       67     34       66      78
15   114   Rajesh      45       67     77       66      46

In [46]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social  total
14   113     sonu      60       89     98     87       77      68    479
11   111   Ritchi      66       68     64     76       98      75    447
13   112  shareef      50       63     99     90       76      67    445
16   115   Rakesh      67       78     88     78       67      49    427
2    102   Rossum      56       88     56     99       44      77    420
7    107  Praveen      46       88     74     86       78      45    417
6    106   Kambli      53       81     59     92       48      73    406
9    109     Nags      55       77     44     77       86      58    397
0    100   Ramesh      50       60     66     98       66      55    395
8    108   Ganesh      53       62     76     88       76      35    390
10   110    Biswa      66       48     86     95       48      47    390
4    104   Kalyan      51       63     62     93       67      51    387
12   104   Kalyan      51       63     62     93       67      51    387
5    105  Karthik      48       62     39     68       65      88    370
3    103     Raji      56       78     34     56       88      55    367
1    101   Rajesh      45       67     34     67       66      78    357
15   114   Rajesh      45       67     77     55       66      46    356

In [47]:
#Remove Multiple Column Names from DataFrame
a.drop(columns=["maths","total"],inplace=True)

In [48]:
print(a)

    htno     name  telugu  english  hindi  science  social
14   113     sonu      60       89     98       77      68
11   111   Ritchi      66       68     64       98      75
13   112  shareef      50       63     99       76      67
16   115   Rakesh      67       78     88       67      49
2    102   Rossum      56       88     56       44      77
7    107  Praveen      46       88     74       78      45
6    106   Kambli      53       81     59       48      73
9    109     Nags      55       77     44       86      58
0    100   Ramesh      50       60     66       66      55
8    108   Ganesh      53       62     76       76      35
10   110    Biswa      66       48     86       48      47
4    104   Kalyan      51       63     62       67      51
12   104   Kalyan      51       63     62       67      51
5    105  Karthik      48       62     39       65      88
3    103     Raji      56       78     34       88      55
1    101   Rajesh      45       67     34       66      78
15   114   Rajesh      45       67     77       66      46

In [49]:
a.columns

Index(['htno', 'name', 'telugu', 'english', 'hindi', 'science', 'social'], dtype='str')

In [50]:
a.columns[0]

'htno'

In [51]:
a.columns[[0,6]]

Index(['htno', 'social'], dtype='str')

In [53]:
#Remove the Science Column from Data Frame Based Its Col Index
a.drop(columns=a.columns[5])

    htno     name  telugu  english  hindi  social
14   113     sonu      60       89     98      68
11   111   Ritchi      66       68     64      75
13   112  shareef      50       63     99      67
16   115   Rakesh      67       78     88      49
2    102   Rossum      56       88     56      77
7    107  Praveen      46       88     74      45
6    106   Kambli      53       81     59      73
9    109     Nags      55       77     44      58
0    100   Ramesh      50       60     66      55
8    108   Ganesh      53       62     76      35
10   110    Biswa      66       48     86      47
4    104   Kalyan      51       63     62      51
12   104   Kalyan      51       63     62      51
5    105  Karthik      48       62     39      88
3    103     Raji      56       78     34      55
1    101   Rajesh      45       67     34      78
15   114   Rajesh      45       67     77      46

In [54]:
print(a)

    htno     name  telugu  english  hindi  science  social
14   113     sonu      60       89     98       77      68
11   111   Ritchi      66       68     64       98      75
13   112  shareef      50       63     99       76      67
16   115   Rakesh      67       78     88       67      49
2    102   Rossum      56       88     56       44      77
7    107  Praveen      46       88     74       78      45
6    106   Kambli      53       81     59       48      73
9    109     Nags      55       77     44       86      58
0    100   Ramesh      50       60     66       66      55
8    108   Ganesh      53       62     76       76      35
10   110    Biswa      66       48     86       48      47
4    104   Kalyan      51       63     62       67      51
12   104   Kalyan      51       63     62       67      51
5    105  Karthik      48       62     39       65      88
3    103     Raji      56       78     34       88      55
1    101   Rajesh      45       67     34       66      78
15   114   Rajesh      45       67     77       66      46

In [55]:
#Remove the Science Column from Data Frame Based Its Col Index
a.drop(columns=a.columns[5],inplace=True)

In [56]:
print(a)

    htno     name  telugu  english  hindi  social
14   113     sonu      60       89     98      68
11   111   Ritchi      66       68     64      75
13   112  shareef      50       63     99      67
16   115   Rakesh      67       78     88      49
2    102   Rossum      56       88     56      77
7    107  Praveen      46       88     74      45
6    106   Kambli      53       81     59      73
9    109     Nags      55       77     44      58
0    100   Ramesh      50       60     66      55
8    108   Ganesh      53       62     76      35
10   110    Biswa      66       48     86      47
4    104   Kalyan      51       63     62      51
12   104   Kalyan      51       63     62      51
5    105  Karthik      48       62     39      88
3    103     Raji      56       78     34      55
1    101   Rajesh      45       67     34      78
15   114   Rajesh      45       67     77      46

In [57]:
#Remove the Telugu,English and social Columns from Data Frame Based Its Column Indices
a.drop(columns=a.columns[[2,3,5]],inplace=True)

In [58]:
print(a)

    htno     name  hindi
14   113     sonu     98
11   111   Ritchi     64
13   112  shareef     99
16   115   Rakesh     88
2    102   Rossum     56
7    107  Praveen     74
6    106   Kambli     59
9    109     Nags     44
0    100   Ramesh     66
8    108   Ganesh     76
10   110    Biswa     86
4    104   Kalyan     62
12   104   Kalyan     62
5    105  Karthik     39
3    103     Raji     34
1    101   Rajesh     34
15   114   Rajesh     77

In [60]:
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [61]:
#Remove 10 Record
a.drop(index=10,axis=0)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [62]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [64]:
#Remove 3 and 13 Indices Records
a.drop(index=[3,13],axis=0)   #a.drop(labels=[3,13],axis=0)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [65]:
#Remove 0 and 16 Indices Records
a.drop(index=[0,16],axis=0)

    htno     name  telugu  english  hindi  maths  science  social
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46

In [66]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [68]:
#Remove 0 and 16 Indices Records
a.drop(index=[0,16],axis=0,inplace=True)

In [69]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46

In [70]:
#Adding the Row to the Data Frame
import pandas as pd
a=pd.read_csv("F:\\Python-Libraries\\Pandas\\Studentmarks.csv")
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49

In [71]:
len(a)

17

In [72]:
a.loc[17]=[134,"BB",89,79,86,98,86,90]

In [73]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
17   134       BB      89       79     86     98       86      90

In [74]:
a.loc[len(a)]=[122,"RS",88,98,87,90,95,85]

In [75]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
17   134       BB      89       79     86     98       86      90
18   122       RS      88       98     87     90       95      85

In [76]:
#Duplicates

In [77]:
a.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [78]:
a.loc[a.duplicated()]

    htno    name  telugu  english  hindi  maths  science  social
12   104  Kalyan      51       63     62     93       67      51

In [82]:
#Drop the  Duplicate Records from DataFrame Object
a.drop_duplicates()

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
17   134       BB      89       79     86     98       86      90
18   122       RS      88       98     87     90       95      85

In [83]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
12   104   Kalyan      51       63     62     93       67      51
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
17   134       BB      89       79     86     98       86      90
18   122       RS      88       98     87     90       95      85

In [84]:
a.drop_duplicates(inplace=True)

In [85]:
print(a)

    htno     name  telugu  english  hindi  maths  science  social
0    100   Ramesh      50       60     66     98       66      55
1    101   Rajesh      45       67     34     67       66      78
2    102   Rossum      56       88     56     99       44      77
3    103     Raji      56       78     34     56       88      55
4    104   Kalyan      51       63     62     93       67      51
5    105  Karthik      48       62     39     68       65      88
6    106   Kambli      53       81     59     92       48      73
7    107  Praveen      46       88     74     86       78      45
8    108   Ganesh      53       62     76     88       76      35
9    109     Nags      55       77     44     77       86      58
10   110    Biswa      66       48     86     95       48      47
11   111   Ritchi      66       68     64     76       98      75
13   112  shareef      50       63     99     90       76      67
14   113     sonu      60       89     98     87       77      68
15   114   Rajesh      45       67     77     55       66      46
16   115   Rakesh      67       78     88     78       67      49
17   134       BB      89       79     86     98       86      90
18   122       RS      88       98     87     90       95      85

In [86]:
a.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [87]:
a.loc[a.duplicated()]

Empty DataFrame
Columns: [htno, name, telugu, english, hindi, maths, science, social]
Index: []